import styles from "./LayoutStyles.module.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.header}>Priyanshu Idea Usher</div>
        {children}
      </body>
    </html>
  );
}
